### ISSUE TITLE
Inconsistent spacing

### ISSUE THREAD

**Issue by Hubcapp** [Pizzacus/satania.moe#13]
highlighted in magenta, see https://i.imgur.com/JAqiDDi.jpg

**Comment by Pizzacus** [comment]
Woah what? There isn't supposed to be spacing there at all! Normally the picture touches the borders of the blocks...

Might have to do with your screen size... I didn't test the website under a lot of different sizes...

I'll take a look at it once I return back home in a few days, right now I'm stuck on my phone.

Thanks for reporting! That isn't normal at all.

**Comment by Pizzacus** [comment]
Should hopefully be fixed in 63239765a955de41c28edd2bc78dbf18cb004882

I thought it'd be a bug that only happens with some weird resolution or device, so I felt like fixing it would be super hard.

But no it was just on Firefox (and possibly other browsers?) and I have no idea how I never noticed it before.
