### ISSUE TITLE
More language i guess?

### ISSUE THREAD

**Issue by guccidan** [Pizzacus/satania.moe#23]
alright.. so I never watched G.D.  (plan to watch it thou lol)
idk about anythin about this show... but i jus like this stuff lol 

and i noticed there is Japanese there
i thought adding Korean would work too lol

i would be glad to help you out lol 

im native on both Kor/Eng.

**Comment by Pizzacus** [comment]
Oh hey, thanks a lot, that is a great suggestion, we get a lot of visits from Koreans (way more than from Japanese people according to Google Analytics), so a Korean translation would be sweet.

I do know Korean people but none want to help me with it ;-;

There is a wiki about how to translate if you're interested but it is a bit out of date, usually translators are people I know on Discord so I just explain them directly

Also I'm writing this on mobile as I can't use my computer until Friday, so I can't really double check that

1. Go to <https://satania.moe/#translator-mode>, buttons will appear on the top left

1. Click "Download" to get a copy of the translation files

1. Edit the file, it's a very obvious format, you can preview your changes by clicking the "browse" button to pick your file, nothing will be uploaded it happen in your browser

1. Once you're good either send me the file on GitHub or on Discord at Pizzacus#7746, or you can do a pull request if you know how to do it, you would have to add your translation to the \<select> in index.html and put it in the locale folder in src/, you don't have to do it if you don't want to

Also while translating, ignore all the HTML tags like \<i> or \<b>, you should not translate them and their attributes

If you have a doubt about something remember you can preview your translation ^_^

Also if you give up or anything that's fine, no one is perfect...

Except Satania she is perfect uwu!!!!!!!!

**EDIT:** Woops using HTML Tags messed up the way the list looked, sorry if it looked silly ._.

**Comment by guccidan** [comment]
i'm actually workin on it right now...
i think it would be done before Friday KST. 

lil prob is, yesterday it worked but now "browse" thing aint workin... 

sorry i aint dat pro @ coding and stuff.. 

so... like i do hav copy downloaded and fixin it,
i tried to see my progress, but cant see

**Comment by StimpaC-MarineS** [comment]
[](url)

**Comment by Pizzacus** [comment]
if browse isn't working it means the file is broken (I know I should display an error code, it's a bit silly lol)

Tho the file you sent me on Discord seems fine, so maybe a refresh would have fixed it or idk, tho you forgot a few parts, I'll tell you which in DMs

**Comment by Pizzacus** [comment]
So I thought I would go back on this issue to thank you for translating satania.moe again!

(I sent you a message on Discord earlier but I know you don't really check it, while GitHub sends mail notifications for new comments so I thought I'd do it)

So as you pointed out, [namu.wiki is linking to us](https://namu.wiki/w/%EC%BF%A0%EB%A3%A8%EB%AF%B8%EC%9E%90%EC%99%80%20%EC%82%AC%ED%83%80%EB%8B%88%ED%82%A4%EC%95%84%20%EB%A7%A5%EB%8F%84%EC%9B%B0), at first they were only contributing a very small percentage of our visits, but that has... changed a lot since...

![image](https://user-images.githubusercontent.com/7659613/43950823-befea9a8-9c91-11e8-9618-c0571026dbbc.png)

[**And now, about 15% of our sessions come from South Korea**](https://user-images.githubusercontent.com/7659613/43950840-cbe7c992-9c91-11e8-8af6-6440433d54c6.png)

(Or 10% if you count from the veryyyyy beginning)

I don't have data on how many people use the Korean translation, but I know the following:
  * [Korean is the second most popular language](https://user-images.githubusercontent.com/7659613/43952732-1403908a-9c97-11e8-9f5a-41ac71bb3976.png) (**according to the system language**, not the actual language they pick on the website)
  * [Only 2.78 % of our Korean users can speak english](https://user-images.githubusercontent.com/7659613/43951129-8dfa430c-9c92-11e8-971a-9811cea8592e.png), so Koreans aren't good at English, which makes the translation even more important
  * ...to compare, [16.79 % of people from Brazil can speak English](https://user-images.githubusercontent.com/7659613/43952175-6ac95ffa-9c95-11e8-9427-980f9ebbbdd5.png), so SOME countries are good at English, but Korea isn't one of them, so they really need a translation
  * (and both countries have a few Japanese weirdos in them)

---------------------------

**So I thought I would say thank you!** Because you created a very crucial translation and thanks to that,  hundreds of users from South Korea discover the website every month

Thanks to translators like you, the power of Satania knows no frontier! >:3 We will become the biggest in the galaxy! >w<

So yeah...

## Thank you for helping us early on ♥

Your reward is a good people card:

![](https://user-images.githubusercontent.com/7659613/43953811-88b18c72-9c9a-11e8-85f1-4b7777fe4680.jpg)
