### ISSUE TITLE
Image Compression (Convert everything to WEBP)

### ISSUE THREAD

**Issue by LorenzoRamalho** [Pizzacus/satania.moe#25]
Would recommend sending the images (like the first background, *app/assets/img/back.jpg*) through a compressor to improve load time. [TinyPNG](https://tinypng.com) is a pretty good one.

And maybe even convert them to JPEG since it has more compression. But without degrading too much the quality of course.
You'll be the judge 😃

**Comment by Pizzacus** [comment]
Hi, thanks for looking into it! But the images are already compressed.

The backgrounds are in JPG in a compression rate that I estimated back then gave the best quality/size compromize, but the images requiring transparency are in PNG, but they should have been optimized as much as the format allows it, but they are still quite heavy : /

**That is because PNG is not a lossy format**, you cannot use it to make very small images, JPG is a lossy format, good for compression, but it can't have transparency.

I am considering instead to convert everything to WEBP, a superior image format, said to potentially replace JPG and PNG in the future, as it is able to do lossy compression with transparency.

Although **it is** supported in Firefox and Chrome, there is still a poor support across other browsers, so I would use img[srcset] in order to let browser decide if they want a new compressed and bleeding edge WEBP or a good old PNG/JPG if they don't support webp.

There is probably a way to get brunch to automatically convert stuff to webp and if not I can do it manually.

Also i just wanna point out that online services should be avoided to compress images. As it means that your image ends up on their computer forever and there are better ways to do it.

You should check the Wikimedia guide for [preparing images for upload](https://commons.wikimedia.org/wiki/Commons:Preparing_images_for_upload) and particularily the section on [PNG compression](https://commons.wikimedia.org/wiki/Commons:Preparing_images_for_upload#PNG_tips) which recommends using softwares such as the excellent [OptiPNG command line tool](http://optipng.sourceforge.net/).

Images are a big deal on satania.moe, they make up a large part of the data transferred and it is indeed something that should be dealt with, I need to admit I had kinda forgotten about it so I am gonna get on it soon now xD

**EDIT**: Firefox definitely cant display webp actually rip

**Comment by friendlyanon** [comment]
I would advise against using WEBP, since it has many flaws, not having the best compression ratio possible and not being cross platform are among them. But if cross platform support is not of concern then:
Enter the FLIF image format. http://flif.info/
It would be a far better solution which provides a polyfill for displaying FLIF images and a far smaller compression size with various other benefits.

**Comment by Pizzacus** [comment]
~~I actually had totally forgotten this issue, I don't really actively work on it because satania.moe is not the kind of website that you would really spend all your time improving~~

That being said, you bring up interesting points!

* **Bad browser support.** I was gonna use srcset to let the browser figure it out anyway, but I do realize ~~only Google Chrome users would have enjoyed the performance boost~~ **oh wait, Firefox and Edge now both support webp in their nightly, so they'll probably gonna support it soon in stable, we still need a supported fallback though**
* **Bad compression** Still waaay better than PNG that doesn't allow things to be compressed very much at all and GIF is just terrible, all we need is good lossy compression with transparency, that would already be a HUGE help, even if it's not the best compression out there

However, this isn't at all to dismiss the qualities of FLIF, it does appear to be a more robust format than WEBP, buuuut, satania.moe is just a small fun website, I'm not even sure if I will ever implement this issue at all, and I don't plan to use a FLIF polyfill just to load the images.

However, I did try the Polyfill tech demo and I can say it's extremely impressive.

The website isn't even THAT big, it is probably above average just because of images, and thats pretty dumb, yes, but it could be worse. I have a very bad internet myself and I can say the loading time is still... passable...

But thanks for your suggestion as I wasn't aware of FLIF, if I ever have a need to make an application that needs to load a lot of images, particularly if it's outside of the browser, I will definitely strongly consider it

-------

<sup>One of the thing that would motivate me to implement WEBP would be the fact that it would make @kurogetsusai <a href="https://i.fiery.me/kBYn.png">absolutely hate me</a> and I definitely want that to happen >:D</sup>

**Comment by Pizzacus** [comment]
Oh and you have a great pfp :heart:

**Comment by lunakurame** [comment]
I like FLIF, very cool. :D

There's also another nice image format, [farbfeld](http://tools.suckless.org/farbfeld). It's designed to be the simplest format possible to implement and follow the Unix philosophy, so compression is handled by bzip2 instead. .ff.bz2 files are generally smaller than .png, but idk how to use it on a website, you would have to write your own implementation I guess.

Also WebP is trash, there are way better formats. I'd rather just use PNG because it works everywhere, people can save images and view them in anything, while WebP isn't supported by most image viewers so they'll have to convert them and nobody's gonna do that. If there are any reasons to use WebP (like smaller files or whatever), then there are no reasons not to use FLIF, so why bother with WebP at all.

**Comment by Pizzacus** [comment]
Seems like a primitive version of BMP, that couldn't possibly be smaller than anything

**EDIT:** Yea for instance, [satania_happy.png](https://satania.moe/img/satania_happy.png) is a 282.4 kB PNG file and it's 309.0 kB in farbfeld

If making a good image format was as simple as bzipping raw pixels, we would stop making new ones lol

**EDIT 2:** On the other hand it was 160 kB in lossless FLIF and 67.7 kB in 80% lossy, which is extremely impressive

That same image is 182.3 kB in lossless webp so its also a good improvement, it can get lower in lossy but its not relevant to compare lossy quality size as "80% lossy" doesn't mean the same thing across all formats

**Comment by lunakurame** [comment]
Depends on the pic, eg. [this](https://i.redd.it/wx2qj57vp9v11.png) is 1 MB in PNG and 469 kB in ff.bz2. Less than half the size vs 20 kB more for your pic.

**Comment by Pizzacus** [comment]
YES FINALLY I ADDED IT xD

Note that rn the production building process is broken but I'm fixing it soon (by finally upgrading from Brunch)

**Comment by Pizzacus** [comment]
Ok, building was fixed so you can now see the webp live!
