### ISSUE TITLE
Autism

### ISSUE THREAD

**Issue by negatron99** [Pizzacus/satania.moe#42]
What you say about autism doesn't preclude the possibility that she's autistic.

Plenty of autistic people are extroverts and quite capable of being outward and like her.

She could be Asperger's (still autistic).

**Comment by Pizzacus** [comment]
(Really thought I had replied to this issue)

When I made satania.moe, I was on a Discord server called Gabriel Dropout, which had a lot of people bullying Satania. >:[

So the primary audience were those people, I had no idea the website would become viral as it did.

The bullies on GabDrop often said that Satania was autistic. So it was something I just *had* to address. I had to say something about this because it was such a common accusation.

Also, the development of satania.moe was a tiny bit rushed. I didn't have time to do a lot of things properly, and this was reflected in my poor research on autism. I remember that as I was writing this, I was really unsure about what I was doing, and I was hoping no one would fact-check me. xD

--------------------

I am sorry if this upsets you, but I am not planning to change the website. First, because a change in the text requires me to get a hold of every translator and that's about 20 people in various places.

Secondly, because I see satania.moe as a sort of art. I don't want to sound pretentious here, it's not art like a beautiful painting or an incredible film. But it is art as in the fact that it aims to entertain people. It's something you are meant to appreciate, not use like a regular website.

And satania.moe as an artwork has a lot of emotional value to me because it's the website that created Satania Dropout, an online community which has existed for over two years now and has thousands of members.

Because of that, I feel reluctant in **modifying** satania.moe. I have added several new things in the past, like the music player or the easter egg if you click the nose of the Satania reindeer. But I didn't change any of the **existing** elements. Because they reflect our origin, they reflect the state of mind in which I made satania.moe.

And yet there are a lot of things that could be changed. Some of the text is awkward (like the one in the section that explains how Satania replaces other waifus) and some jokes could be improved. But this is part of what makes satania.moe special to me.

I will have the opportunity to polish future anime meme websites better. In fact, we have some websites in the work that will be 100x more polished than satania.moe. I'd rather learn from my mistakes in newer websites rather than "cheat" and pretend like everything was always perfect.

I want to make new meme websites. And maybe in the future, I'll be able to compare these to satania.moe and see how much I progressed. 

----------------------

Now, this statement has to be taken with a bit of a grain of salt. I did do an update recently (August 14th IIRC) that changed a bit of the design of satania.moe. :x 

It did a few changes on the desktop version (like how the text saying "The best waifu. Ever" now has a red background to make it more readable) and major changes to the mobile version. This forced me to [remove a banner warning people that the mobile version is pretty bad](https://github.com/Pizzacus/satania.moe/blob/master/src/index.html#L152).

I can understand that this may be contradictory with what I just said. And frankly, I was very torn about this update.

I think that a few minor changes are acceptable. I tried to stay in line with the kind of design I was doing at the time. I was feeling very guilty for having completely overlooked the mobile version (turns out 50% of our visits come from phones because satania.moe is mainly shared on social networks and those have a high mobile usage rate). And my guilt for having messed up that part was stronger than my desire to keep the website intact. xD

But I don't think the part about autism is a major issue like the mobile version was.

----------------------------

I did consider some methods to correct the section without changing the website too much. Like adding a little star (\*) after the title linking to this issue. Buuut, I think this would be shooting myself a bullet in the foot. Essentially, I would be saying "Satania isn't an autist\*" "\*actually she may be".

Satania.moe is meant to praise Satania, so doing this doesn't feel right. It would also make the website harder to understand since it would be contradicting itself.

If we want to fix this section, we have to change the text, and I am not willing to do that.

So yeah, sorry if you expected me to fix this issue. Although you didn't ask me to change it, you just fact-checked me so maybe that will be alright to you. I hope you understand my viewpoint and this doesn't come off to you as hostile, incoherent, or stubborn. :x

**Comment by Pizzacus** [comment]
It won't let me add the "Pizzacus finally did something after waiting for weeks!" label D:

![image](https://user-images.githubusercontent.com/7659613/64075125-80e23a00-ccb4-11e9-81e2-c159968c3513.png)

**Edit**: Oh there we go, turns out GitHub changed the maximum label name length so this label was grandfathered and unusable.

**Comment by negatron99** [comment]
Thank you for the response... yeah that's fine.
