### ISSUE TITLE
Replace Satania with Gabriel

### ISSUE THREAD

**Issue by ghost** [Pizzacus/satania.moe#59]
like seriously, all of you just like her because she's dumb and acts like a dog half the screentime.

There's a reason it's called **Gabriel** Dropout and not *Satania* Dropout and that's because she's effectively 
just another irrelevant side character that is only there to boost Raphiel's sadism. 

Half of the reason's she is considered superior on your site are appeals to majority, which as we've seen in history is always a great way to differentiate something as better.

Gabriel on the other hand is clearly superior, here only a few examples out of the seemingly infinite pool of reasons why one would consider her to be the best of them all:

- most responsible character in the whole series, god gave her the power to literally destroy humanity with one blow and yet we still are alive (as of september 2020)
- most powerful girl in the series (see above)
- has the ability to teleport stuff around, you dont see satania show any cool magic tricks (and her familiar is pathetic, even vignes **pet** is several oders of magnitudes stronger)
- can cure diseases
- can fly
- gamer girl
- pretty smart, is shown several times to write good grades just from studying with vigne a couple minutes before the teacher comes in
- if she messes up (see: can cure diseases) she takes her punishment like a big girl, satania is shown to just cry like a entitled whiny bitch (as seen in the first episode)
- doesn't need fancy clothing because she doesn't give a fuck about what other people think of her, only her own opinion of herself is matter and that is a beautiful message to teach viewers in todays society
- chooses to take the path in life that she wants, not what other people expect from her which is once again a beautiful inspiritional message to teach viewers
- gabriel wasted her money only on stuff that help her assist other people in video games, she's just such a great person, while satania spends all her money on useless stuff with the sole purpose of annoying gabriel.
- god good satan bad or something that my grandma told me idk, im not religious
and the list goes on

im not trying to blame you here or ridicule you, mistakes happen and we all do them all the times. some mistakes are small and have no real impact on others (accidentally wearing mismatching socks, forgetting your keys, using a strcmp in the security relevant code of your game console) but there are also big, fatal mistakes that have the potential to endanger an entire generation (sending off that nuclear missile by mistake or accidentally teaching people about the wrong waifu). but late is better than never and you can always correct your mistakes.

im looking forward to seeing this website at a later point, shining in the image of the real best waifu of all times and until then have a good day, may gabriel be with you.

Sincerely,
dennthegabriellovingcafebabe

~~please dont take this so seriously, i just typed this for a quick joke in a discord server and some people told me to actually post it~~

**Comment by Pizzacus** [comment]
Thanks for sharing your thoughts and writing such a well-argued and thorough essay! Gabriel is cute! I enjoy her art a lot, and I would buy a daki of her.

However, when it comes to deciding who should rule over humanity and become our supreme overlord, I don't think Gabriel is a good leader, or even, a decent person. I believe Gabriel has critically negative traits that make her cancerous, toxic, and harmful to have as an overlord angel. If she were to rule the world instead of Satania, I think she'd do so in a discriminatory and unfair way. Let me explain why.

She may have all the abilities you listed, but with the path she's currently following, she won't be in a position to use them for good once she graduates. If she ever does. Because with the way she uses her powers, Gabriel is on the path to becoming a Bastard Angel.

As you said, she cured someone ONCE. And why did she do it? Because they had the greatest need? No. She healed the blind girl because she was a friend.

These actions are part of a critical problem with angels: they apply the law only as they think is right. They discriminate in the way they summon miracles and use their powers. Discretionary decision-making allows angels to pick and choose who gets a pass, and who will have to deal with their problems themselves.

This preferential treatment is the main factor behind the **All Angels Are Bastard** protests, calling for reforms of the Kingdom of Heaven.

I understand why Gabriel saving lives might feel like a good thing. But it's harmful when so much bias and prejudice is involved in it. Gabriel is just as bad as most other angels.

Satania, on the other hand, doesn't discriminate. I believe Satania will spare everyone who follows her from the armageddon she will bring once she's in control. Satania is a fair ruler, and she's cute as well. I trust her with the fate of humanity far more than I trust Gabriel with it. Praise Satania!

And no, I'm not actually that socialist in real life!

**Comment by ghost** [comment]
May gabriel have mercy with your lost soul..

PS: A friend of mine is called gabrielle and she's a big cutie and the name sounds similar so that alone invalidates every counter argument of yours

**Comment by Pizzacus** [comment]
Hi just randomly checking in, has your opinion changed? Have you seen the ~~light~~ darkness?

**Comment by ghost** [comment]
i-i haven't thought so far.
im gonna close this, it was a good quick joke but i'm not funny enough to keep this going without it embarassing me lol.

so yeah, c ya, nice talking to ya and maybe someday we can talk some more about your objectively wrong opinion :P

**Comment by Pizzacus** [comment]
![uGXFU_0w_400x400](https://user-images.githubusercontent.com/7659613/94008238-f7137c00-fda2-11ea-8ee2-9ede68d2c51d.jpg)
